
server:
  port: 7070
 
  servlet:
    context-path: /lts-spring-boot
 
spring:
  profiles:
    active:
    - dev

  autoconfigure:
    exclude:
    - 

  http:
    log-request-details: true

# spring.devtools.restart.enabled 禁用devtools自动重启功能，直接用IDE的热部署
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java

lts: 
#  jobclient:
#    cluster-name: SCHEDULER_CLUSTER
#    node-group: lts-spring-boot
#    registry-address: zookeeper://192.168.5.11:2181    
  # 任务追踪器  
  tasktracker: 
    # 集群名称，对应远程JobTracker服务的配置 (jobtracker.cfg)
    cluster-name: test_cluster
    # 项目名称 (执行节点组名称)
    node-group: lts-spring-boot
    # 提交节点集群名称
    registry-address: zookeeper://192.168.5.11:2181
    
    # 工作线程数
    work-threads: 20
    configs:
      # 失败存储方式
      job.fail.store: mapdb
    # 运行转发器
    job-runner-class: com.hua.dispatcher.JobRunnerDispatcher









